[config]
page_numbers = true

[[pages]]
template = "Cover"
title = "*The Unknown:* <br> Unveiling the Wonders <br> of the Universe"

[[pages]]
template = "Basic"
title = "A Journey Through the Cosmos"
text = """
- In the _vastness of space_, time and distance are but mere illusions
    - Worlds exist beyond our wildest imaginations
        - On these worlds, _beings of all shapes and sizes_ dwell
- With societies and cultures _as diverse as the stars_ that light up the skies above
- They are **united** in their quest for knowledge and understanding
- The universe itself is our teacher, and its secrets our endless source of inspiration
"""

[[pages]]
template = "TitleMultiColumn"
title = "In the Vastness of Space, Time and Distance Are but Mere Illusions"
text = [
"Amidst the lush forests and shimmering lakes, ancient beings of immense power and wisdom dwell, watching over the affairs of mortals with a watchful eye.",
"With societies and cultures as diverse as the stars that light up the skies above. On these worlds, beings of all shapes and sizes dwell.",
"The universe itself is our teacher, and its secrets our endless source of inspiration",
]

[[pages]]
template = "Basic"
title = "The Verdant Lands"
text = """
**Amidst the lush forests and shimmering lakes**, ancient beings of immense power and wisdom dwell, watching over the affairs of mortals with a watchful eye.
![image](small-placeholder.svg)
"""

[[pages]]
template = "FullPageDiagram"
title = "Phoenix"
diagram_font_size = "28px"
diagram = """
                            .-==========
                         .-' O    =====
                        /___       ===
                           \\_      |
_____________________________)    (_____________________________
\\___________               .'      `,              ____________/
  \\__________`.     |||<   `.      .'   >|||     .'__________/
     \\_________`._  |||  <   `-..-'   >  |||  _.'_________/
        \\_________`-..|_  _ <      > _  _|..-'_________/
           \\_________   |_|  //  \\\\  |_|   _________/
                      .-\\   //    \\\\   /-.
      ,  .         _.'.- `._        _.' -.`._         .  ,
    <<<<>>>>     .' .'  /  '``----''`  \\  `. `.     <<<<>>>>
      '/\\`         /  .' .'.'/|..|\\`.`. `.  \\         '/\\`
      (())        `  /  / .'| |||| |`. \\  \\  '        (())
       /\\          ::_.' .' /| || |\\ `. `._::          /\\
      //\\\\           '``.' | | || | | `.''`           //\\\\
      //\\\\             .` .` | || | '. '.             //\\\\
      //\\\\                `  | `' |  '                //\\\\
      \\\\//                                            \\\\//
       \\/                      MJP                     \\/
"""

[[pages]]
template = "Basic"
title = "Time and Space"
text = """
The human mind, too, is a wonder of the universe, capable of unlocking the secrets of existence and pushing the boundaries of what we know to be true. Through science and philosophy, we seek to understand the nature of reality. <br>

But as we delve deeper into the unknown, we come to realize that the universe is not always as it seems. Time and space warp and twist, and the very fabric of reality is subject to change. And as we grapple with the implications of our discoveries, we are forced to confront the fundamental questions of our existence.
"""

[[pages]]
template = "FullPageImage"
image = "/large-placeholder.svg"
object_fit = "contain"

[[pages]]
template = "Basic"
title = "The System"
text = """
The console flickers to life as he approaches, the `lines of code` transforming into a stream of data that flows across the screen. He studies the data, his eyes scanning over the numbers and symbols with practiced ease.

```js
function processSensorData(sensorData) {
  if (implant.isActive() && sensorData.value > implant.getThreshold()) {
    implant.triggerAlert();
  }
}
```
"""

[[pages]]
template = "HalfPage"
title = "Mr. Whiskers"
text = """
He sat atop the garden wall, his fur ruffled by the autumn breeze. <br>

He watched as the leaves danced in the wind, their vibrant colors a symphony of beauty.
"""
diagram_font_size = "24px"
diagram = """
                 o   
                .  
              ,'  `.  
            ,'      `.
          ,'          `.
        ,'              `. 
      ,'                  `. 
    ,'                      `.
 _,'__________________________`._
|.------------------------------.|
||                              ||
||      i~.           .~i       ||
||      (:.`..-~~~-..'.:)       ||
||      i: '  : : :  ` :i       ||
||      :°  :_ : : _:  °:       ||
||      !:.: o`. .'o :.:!       ||
||      "L:_` .'_`. '_:J"       ||
||       `:-:: `.' ::-:'        ||
||        )~-. -^- .-~(         ||
||       : :((`~-~')): :        ||
||      (.`._  -:-  _.'.)       ||
||      /\\._  ~`·.·'~  _.\\      ||
||     i-._~·-..·..-·~_.-i   adl||
||______________________________||
`--------------------------------'
"""

[[pages]]
template = "HalfPage"
title = "Mr. Whiskers"
text = """
He sat atop the garden wall, his fur ruffled by the autumn breeze. <br>

He watched as the leaves danced in the wind, their vibrant colors a symphony of beauty.
"""
image = "/large-placeholder.svg"

[[pages]]
template = "Cover"
title = "_Thank you!_"


# [[pages]]
# custom_template = true
# template = "New"
# number = 0